mocks:
	go generate ./...
test-coverage:
	go test ./... -cover -coverprofile=coverage.out
	go tool cover -html=coverage.out -o coverage.html
test:
	go test ./...
	govulncheck ./...
	gosec -quiet ./...
	go vet ./...
	golangci-lint run ./...	
bench:
	go test -bench=. ./... -benchmem
act-ci-test:
	DOCKER_HOST=`docker context inspect --format '{{.Endpoints.docker.Host}}'` act push -v -n